version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: vizchemlab-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-vizchemlab}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "0.0.0.0:5433:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: vizchemlab-backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-vizchemlab}
      SECRET_KEY: ${SECRET_KEY:-your-secret-key}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8000
      GIGACHAT_CLIENT_ID: ${GIGACHAT_CLIENT_ID:-019cd259-c72e-75cb-84b9-b0588a762d74}
      GIGACHAT_AUTH_KEY: ${GIGACHAT_AUTH_KEY:-MDE5Y2QyNTktYzcyZS03NWNiLTg0YjktYjA1ODhhNzYyZDc0OjE3NDlkZDg5LTI1MGMtNDFhNy05ZDYzLWE1MzIyMzUyMGIxZg==}
      PYTHONPATH: .
    ports:
      - "0.0.0.0:8000:8000"
    command: >
      sh -c "python manage_db.py seed && 
             python app/main.py"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: vizchemlab-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "0.0.0.0:80:80"

volumes:
  postgres_data:
