"""add history_type to search_history

Revision ID: f63e2d10132f
Revises: fa9b8fb78edf
Create Date: 2025-12-30 00:48:09.724205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f63e2d10132f'
down_revision: Union[str, Sequence[str], None] = 'fa9b8fb78edf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_history', sa.Column('history_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_history', 'history_type')
    # ### end Alembic commands ###
